### ISSUE TITLE
Guardian Chest Does not play nice with AM2 soulbound gear

### ISSUE THREAD

**Issue by Zieg777** [DrasticDemise/Simply-Magic#23] opened 2016-01-28 08:18 UTC
I just lost my earth armor (with several tiers of upgrades) as well as my arcane spellbook filled with all my spells. I think the soulbound part does not work. There was a hopperhock nearby. It also seems to have duplicated a lot of my other items when the chest explodes with the stuff. I apparently have 2 "normal" spellbooks now as well. No spells, but they both have looting and fortune 3 (I had a fortune 3 dig spell equipped when I died.

**Comment by Zieg777** [comment] 2016-01-28 08:24
In retrospect. This may actually be on Botania or AM2.

I remember I was having difficulty in Hubris. I was trying to use a weight lens to silk touch ores. AM2 ores would turn to other ores though. Something with how the item IDs are

**Comment by DrasticDemise** [comment] 2016-01-29 19:03
Hmm. The Guardian Chest mod explicitly states support for AM2 soul bound gear. Does this happen every time with any soul bound enchant?

**Comment by Zieg777** [comment] 2016-01-29 23:15
No. Honestly, I think its actually more with a combination of factors.
-Botania hopperhock nearby.
-Guardian chest exploding with items (more than I could hold since there was armor in the chest too).
-AM2 problem that I had with ores.

I think something with the hopperhock and me picking up items, The chest the hopperhock was sending to got another of EVERY item I had. I'd approach this more like a dupe glitch. Normally if you drop an item, there's a delay before its picked up, by you or by hopperhocks. With the chest exploding, it didn't seem to have that delay, so both of us picked it up at once.

I can't replicate it in my test world

**Comment by DrasticDemise** [comment] 2016-01-31 06:08
Hmm. There isn't much I can do about this, and it appears to be an edge case if soul bound works as intended in standard use. I will close this for now unless you are able to reproduce this consistently.

**Closed by DrasticDemise** 2016-01-31 06:08 UTC
Labels: bug
